### PR TITLE
German locale additions

### PR DESCRIPTION
**Pull request by jannikstdl**
- Added more missing german translations based on the latest (0.1.122) release
- Added missing i18n keys (mostly in tooltips)

There are still some complex html structures fixed in English, I left that as it is for now because adding translation keys for such sections is a bit complicated due to different grammar.

For example in the share chat modal:
Bildschirmfoto 2024-04-28 um 14 28 55

### CODE REVIEW

**Review by Maximilian-Pichler — APPROVED** [review]

**Comment by Maximilian-Pichler** [comment]
LGTM @jannikstdl, danke!

**Comment by Maximilian-Pichler** [comment]
Hi @jannikstdl,

i'm not that familiar with i18n, but should the new translations also be added to `src/lib/i18n/locales/en-US/translation.json` and possibly others too?

**Comment by jannikstdl** [comment]
Yes would not be required but we could ideally add those.  

Because eng is the fallback language the only reason to add these in the en JSON is that others can customize the english text and to copy those strings in their language files. 

But as far as I know you don't have to do that manually there's a script defined `"i18n:parse": "i18next --config i18next-parser.config.ts && prettier --write 'src/lib/i18n/**/*.{js,json}'" ` for that.

**Comment by jannikstdl** [comment]
I triggered that script, now the strings were added https://github.com/Maximilian-Pichler/open-webui/pull/2 thanks :)

**Pull request merged**
